In [3]:
import numpy as np
a=np.array([[1,2,4],[5,8,7]])
print("Array created :\n",a)

Array created :
 [[1 2 4]
 [5 8 7]]


In [6]:
#creating a 3*4 array with all zeros
b=np.zeros((3,4))
print("array with all zeros :\n",b)

array with all zeros :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
#create a constant value array
c=np.full((3,3),6)
print("Array with all 6s:\n",c)

Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
